# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3505149c2ee8a05ccf313cf44cf812da49da7c3978aad0c9fcc7fdaaa0af9c1df7869d4617525f0b34cb828c9fc0372ea6b7ed58ddaaae797f5c4db1ca61e6bc
  redis_url: "redis://localhost:6379/0"

test:
  secret_key_base: 4e23981ac6670ce1ebd75414a8fe736a9ba609f6ef1f477aca2529d3e66d180c8a92d33f5cc5d75518757492e511d6c20b6ea21ec9766ce5faffdb5cae1a23b4
  redis_url: "redis://localhost:6379/1"

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis_url: <%= ENV['REDISTOGO_URL'] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  redis_url: <%= ENV['REDISTOGO_URL'] %>
